// Copyright (c) 2026 Abdullah Al-Sakni. All rights reserved. DYLLU Catalog.
export const brand = {
  lime: "#D0DF00",
  limeDark: "#B4C100",
  ink: "#2B2D2F",
  gray: "#63666A",
  accent: "#FF6900",
  soft: "#F4F5F5",
  line: "#E6E7E8",
};
export const defaultSettings: Record<string, string> = {
  "home.title.ar": "أدوات ومعدات DYLLU احترافية لكل استخدام",
  "home.title.en": "Professional DYLLU tools for every job",
  "home.sub.ar": "معدات DYLLU بجودة تعتمد عليها",
  "home.sub.en": "DYLLU equipment you can rely on",
  "hero.image": "",
  "footer.text.ar": "أدوات ومعدات احترافية",
  "home.cta.en": "Browse products",
  "home.cats.ar": "التصنيفات",
  "home.cats.en": "Categories",
  "home.featured.ar": "المنتجات المميزة",
  "home.featured.en": "Featured",
  "home.new.ar": "وصل حديثًا",
  "home.new.en": "New arrivals",
  "home.allCats.ar": "عرض كل التصنيفات",
  "home.allCats.en": "View all categories",
  "home.allProducts.ar": "عرض كل المنتجات",
  "home.allProducts.en": "View all products",
  "home.allFeatured.ar": "عرض كل المنتجات المميزة",
  "home.allFeatured.en": "View all featured",
  "search.ph.ar": "ابحث باسم المنتج أو رقم الموديل",
  "search.ph.en": "Search by product name or model",
  "footer.text.en": "Professional tools & equipment",
  "footer.tagline.ar": "DYLLU, Discover your Power",
  "footer.tagline.en": "DYLLU, Discover your Power",
  "home.cta.ar": "استعرض المنتجات",
  "whatsapp.number": "9665XXXXXXXX",
  "contact.phone": "",
  "contact.email": "",
  "contact.address.ar": "",
  "contact.address.en": "",
  "social.instagram": "",
  "social.x": "",
  "social.tiktok": "",
  "social.snapchat": "",
  "logo.url": "",
  "site.name": "DYLLU",
  "price.hiddenLabel.ar": "تواصل معنا",
  "currency.ar": "ريال",
  "currency.en": "SAR",
};
